# docker-compose.yaml

version: '3' # version of docker-compose to use

services: # configuring each container
  db: # name of our mysql container
    image: mysql:5.7 # which image to pull, in this case specifying v. 5.7
    volumes: # data to map to the container
      - ./backups/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz # where to find our data -- we'll talk more about this
    restart: always # always restart the container after reboot
    environment: # environment variables -- mysql options in this case
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: cfacprwe_cfac-sandbox
      MYSQL_USER: cfacprwe_cfacpr
      MYSQL_PASSWORD: "BYUd0mainz"

  wordpress: # name of our wordpress container
    depends_on: # container dependencies that need to be running first
      - db
    build: .
    ports:
      - "8000:80" # setting our ports for networking
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306 # default mysql port
      WORDPRESS_DB_NAME: cfacprwe_cfac-sandbox
      WORDPRESS_DB_USER: cfacprwe_cfacpr
      WORDPRESS_DB_PASSWORD: "BYUd0mainz" # matches the password set in the db container
    volumes: # this is where we tell Docker what to pay attention to
      - ./cfac.byu.edu:/var/www/html/ 